/**
 * teleos — plain-language logic engine for JavaScript/TypeScript.
 *
 * Load a .teleos knowledge base and query it:
 *
 *   import { Teleos } from 'teleos';
 *
 *   const engine = await Teleos.parse(`
 *     fact: alice is admin
 *     rule: if X is admin then X can access Y
 *   `);
 *   engine.ask('alice can access document');   // true
 *   engine.why('alice can access document');   // proof string
 *   engine.all('WHO gets distinction');        // string[]
 *
 * Works in Node.js and the browser (via WebAssembly).
 */

// TeleosEngine is generated by wasm-pack from teleos-core (src/wasm.rs).
// Node.js target loads synchronously — no init() needed.
import { TeleosEngine } from './wasm/teleos_core';

// ─── Result types ─────────────────────────────────────────────────────────────

type SingleVarResult = string[];
type MultiVarResult  = Record<string, string>[];

// ─── Engine class ─────────────────────────────────────────────────────────────

export class Teleos {
  private _engine: TeleosEngine;

  private constructor(engine: TeleosEngine) {
    this._engine = engine;
  }

  /**
   * Load a .teleos knowledge base from a URL (browser) or file path (Node.js).
   *
   *   const engine = await Teleos.load('/rules.teleos');
   */
  static async load(url: string): Promise<Teleos> {
    const text = await fetch(url).then((r) => r.text());
    return Teleos.parse(text);
  }

  /**
   * Load a .teleos knowledge base from a string.
   *
   *   const engine = await Teleos.parse('fact: alice is admin\n...');
   */
  static parse(text: string): Teleos {
    return new Teleos(new TeleosEngine(text));
  }

  // ── Queries ──────────────────────────────────────────────────────────────

  /** Returns true if the goal can be proven. */
  ask(goal: string): boolean {
    return this._engine.ask(goal);
  }

  /** Returns a human-readable proof, or explanation of why the goal fails. */
  why(goal: string): string {
    return this._engine.why(goal);
  }

  /**
   * Returns all solutions to a query containing variables (ALL CAPS terms).
   *
   * Single variable → string[]
   *   engine.all('WHO gets distinction')  // → ['alice', 'eve']
   *
   * Multiple variables → Record<string, string>[]
   *   engine.all('WHO can access WHAT')   // → [{ WHO: 'alice', WHAT: 'document' }, ...]
   */
  all(goal: string): SingleVarResult | MultiVarResult {
    const raw = this._engine.all(goal);
    if (!raw) return [];

    const lines = raw.split('\n').filter(Boolean);
    const goalWords = goal.trim().split(/\s+/);
    const varPositions: number[] = [];

    for (let i = 0; i < goalWords.length; i++) {
      if (/^[A-Z][A-Z0-9_]*$/.test(goalWords[i])) {
        varPositions.push(i);
      }
    }

    if (varPositions.length === 0) return lines;

    if (varPositions.length === 1) {
      const pos = varPositions[0];
      return lines.map((line) => line.split(/\s+/)[pos] ?? line);
    }

    return lines.map((line) => {
      const words = line.split(/\s+/);
      const result: Record<string, string> = {};
      for (const pos of varPositions) {
        result[goalWords[pos]] = words[pos] ?? '';
      }
      return result;
    });
  }

  /** Add a fact to the knowledge base at runtime. */
  addFact(fact: string): void {
    this._engine.add_fact(fact);
  }

  /** Free the underlying WASM engine. Call when done to avoid memory leaks. */
  dispose(): void {
    this._engine.free();
  }
}

// Module-level convenience functions — mirror Python API
export async function load(url: string): Promise<Teleos> {
  return Teleos.load(url);
}

export function parse(text: string): Teleos {
  return Teleos.parse(text);
}

