{
  "models": [
    {
      "title": "Gemini 1.5 Pro",
      "provider": "gemini",
      "model": "gemini-1.5-pro-latest",
      "apiKey": "AIzaSyCL9_KXqeOjNAMmJiINYcJWcOvPifOotFY"
    },
    {
      "title": "Gemini 1.5 Flash",
      "provider": "gemini",
      "model": "gemini-1.5-flash-latest",
      "apiKey": "AIzaSyCL9_KXqeOjNAMmJiINYcJWcOvPifOotFY"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Gemini 1.5 Flash",
    "provider": "gemini",
    "model": "gemini-1.5-flash-latest",
    "apiKey": "AIzaSyCL9_KXqeOjNAMmJiINYcJWcOvPifOotFY"
    },
  "allowAnonymousTelemetry": false
}
